### ISSUE TITLE
make -j8 returns error

### ISSUE THREAD

**Issue by ghlai9665** [CortexFoundation/cvm-runtime#36]
git cloned the wlt branch and make -j8 returns error shown below in the image

![Screen Shot 2020-05-29 at 2 07 33 PM](https://user-images.githubusercontent.com/22721482/83296146-da30b880-a1b5-11ea-8b42-379fb46d862e.png)

**Comment by BetaBeauty** [comment]
The CVM-Runtime does not support the Mac OS currently, the official suggested system contains ubuntu, centos, and redhat, etc.

Two solutions:

1. Launch a ubuntu docker in mac and compile;
2. since the mac error indicates, you may change the Makefile in CVM-Runtime project, find the `cp` command line, and remove the `--update` options. However, It just a simple patch for the specific problem in your mac. You would still encounter many other errors in the later compilation, so you'd better to just follow the first method and wait for our Mac OS support.

Best Regards
